src/OC/PlatformBundle/Entity/Advert.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use OC\PlatformBundle\Validator\Antiflood;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Table(name="oc_advert")
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Repository\AdvertRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 *
 */
class Advert
{
  /**
   * @var int
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="date", type="datetime")
   * @Assert\DateTime()
   */
  private $date;

  /**
   * @var string
   *
   *
   * @ORM\Column(name="title", type="string", length=255)
   */
  private $title;

  /**
   * @var string
   *
   * @ORM\Column(name="author", type="string", length=255)
   * @Assert\Length(min=2)
   */
  private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="mail", type="string", length=255)
     * @Assert\Length(min=2)
     */
    private $mail;

  /**
   * @var string
   *
   * @ORM\Column(name="content", type="string", length=255)
   * @Assert\NotBlank()
   * @Antiflood()
   */
  private $content;

  /**
   * @ORM\Column(name="published", type="boolean")
   */
  private $published = true;

  /**
   * @ORM\OneToOne(targetEntity="OC\PlatformBundle\Entity\Image", cascade={"persist", "remove"})
   * @Assert\Valid()
   */
  private $image;

  /**
   * @ORM\ManyToMany(targetEntity="OC\PlatformBundle\Entity\Category", cascade={"persist"})
   * @ORM\JoinTable(name="oc_advert_category")
   */
  private $categories;

  /**
   * @ORM\OneToMany(targetEntity="OC\PlatformBundle\Entity\Application", mappedBy="advert")
   */
  private $applications;

  /**
   * @ORM\Column(name="updated_at", type="datetime", nullable=true)
   */
  private $updatedAt;

  /**
   * @ORM\Column(name="nb_applications", type="integer")
   */
  private $nbApplications = 0;

  /**
   * @Gedmo\Slug(fields={"title"})
   * @ORM\Column(name="slug", type="string", length=255, unique=true)
   */
  private $slug;

  public function __construct()
  {
    $this->date         = new \Datetime();
    $this->categories   = new ArrayCollection();
    $this->applications = new ArrayCollection();
  }

  /**
   * @ORM\PreUpdate
   */
  public function updateDate()
  {
    $this->setUpdatedAt(new \Datetime());
  }

  public function increaseApplication()
  {
    $this->nbApplications++;
  }

  public function decreaseApplication()
  {
    $this->nbApplications--;
  }

  /**
   * @Assert\Callback
   */
  public function isContentValid(ExecutionContextInterface $context)
  {
    $forbiddenWords = array('démotivation', 'abandon');


    if (preg_match('#'.implode('|', $forbiddenWords).'#', $this->getContent())) {

      $context
        ->buildViolation('Contenu invalide car il contient un mot interdit.')
        ->atPath('content')
        ->addViolation()
      ;
    }
  }

  /**
   * @return int
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @param \DateTime $date
   */
  public function setDate($date)
  {
    $this->date = $date;
  }

  /**
   * @return \DateTime
   */
  public function getDate()
  {
    return $this->date;
  }

  /**
   * @param string $title
   */
  public function setTitle($title)
  {
    $this->title = $title;
  }

  /**
   * @return string
   */
  public function getTitle()
  {
    return $this->title;
  }

  /**
   * @param string $author
   */
  public function setAuthor($author)
  {
    $this->author = $author;
  }

  /**
   * @return string
   */
  public function getAuthor()
  {
    return $this->author;
  }

  /**
   * @param string $content
   */
  public function setContent($content)
  {
    $this->content = $content;
  }

  /**
   * @return string
   */
  public function getContent()
  {
    return $this->content;
  }

  /**
   * @param bool $published
   */
  public function setPublished($published)
  {
    $this->published = $published;
  }

  /**
   * @return bool
   */
  public function getPublished()
  {
    return $this->published;
  }

  public function setImage(Image $image = null)
  {
    $this->image = $image;
  }

  public function getImage()
  {
    return $this->image;
  }

  /**
   * @param Category $category
   */
  public function addCategory(Category $category)
  {
    $this->categories[] = $category;
  }

  /**
   * @param Category $category
   */
  public function removeCategory(Category $category)
  {
    $this->categories->removeElement($category);
  }

  /**
   * @return ArrayCollection
   */
  public function getCategories()
  {
    return $this->categories;
  }

  /**
   * @param Application $application
   */
  public function addApplication(Application $application)
  {
    $this->applications[] = $application;


    $application->setAdvert($this);
  }

  /**
   * @param Application $application
   */
  public function removeApplication(Application $application)
  {
    $this->applications->removeElement($application);
  }

  /**
   * @return \Doctrine\Common\Collections\Collection
   */
  public function getApplications()
  {
    return $this->applications;
  }

  /**
   * @param \DateTime $updatedAt
   */
  public function setUpdatedAt(\Datetime $updatedAt = null)
  {
      $this->updatedAt = $updatedAt;
  }

  /**
   * @return \DateTime
   */
  public function getUpdatedAt()
  {
      return $this->updatedAt;
  }

  /**
   * @param integer $nbApplications
   */
  public function setNbApplications($nbApplications)
  {
      $this->nbApplications = $nbApplications;
  }

  /**
   * @return integer
   */
  public function getNbApplications()
  {
      return $this->nbApplications;
  }

  /**
   * @param string $slug
   */
  public function setSlug($slug)
  {
      $this->slug = $slug;
  }

  /**
   * @return string
   */
  public function getSlug()
  {
      return $this->slug;
  }

    /**
     * Set mail.
     *
     * @param string $mail
     *
     * @return Advert
     */
    public function setMail($mail)
    {
        $this->mail = $mail;

        return $this;
    }

    /**
     * Get mail.
     *
     * @return string
     */
    public function getMail()
    {
        return $this->mail;
    }
}

src/OC/PlatformBundle/Entity/Image.php
<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Table(name="oc_image")
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
  /**
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @ORM\Column(name="url", type="string", length=255)
   */
  private $url;

  /**
   * @ORM\Column(name="alt", type="string", length=255)
   */
  private $alt;

  /**
   * @var UploadedFile
   */
  private $file;


  private $tempFilename;

  /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {

    if (null === $this->file) {
      return;
    }



    $this->url = $this->file->guessExtension();


    $this->alt = $this->file->getClientOriginalName();
  }

  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {

    if (null === $this->file) {
      return;
    }


    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }


    $this->file->move(
      $this->getUploadRootDir(),
      $this->id.'.'.$this->url
    );
  }

  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {

    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {

    if (file_exists($this->tempFilename)) {

      unlink($this->tempFilename);
    }
  }

  public function getUploadDir()
  {

    return 'uploads/img';
  }

  protected function getUploadRootDir()
  {

    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }

  public function getWebPath()
  {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
  }

  /**
   * @return int
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * @param string $url
   */
  public function setUrl($url)
  {
    $this->url = $url;
  }

  /**
   * @return string
   */
  public function getUrl()
  {
    return $this->url;
  }

  /**
   * @param string $alt
   */
  public function setAlt($alt)
  {
    $this->alt = $alt;
  }

  /**
   * @return string
   */
  public function getAlt()
  {
    return $this->alt;
  }

  /**
   * @return UploadedFile
   */
  public function getFile()
  {
    return $this->file;
  }

  /**
   * @param UploadedFile $file
   */

  public function setFile(UploadedFile $file)
  {
    $this->file = $file;


    if (null !== $this->url) {

      $this->tempFilename = $this->url;


      $this->url = null;
      $this->alt = null;
    }
  }
}

src/OC/PlatformBundle/Form/AdvertType.php
<?php

namespace OC\PlatformBundle\Form;

use OC\PlatformBundle\Repository\CategoryRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {


    $builder
      ->add('date',      DateTimeType::class)
      ->add('title',     TextType::class)
      ->add('author',    TextType::class)
        ->add('mail',    TextType::class)
      ->add('content',   CkeditorType::class)
      ->add('image',     ImageType::class, array('required' => false, 'label' => false))
      ->add('categories', EntityType::class, array(
        'class'         => 'OCPlatformBundle:Category',
        'choice_label'  => 'name',
          'multiple'      => true,
        'expanded'      => true,

          'choice_label' => function ($currencies) {
              /** @var Currencies $currencies */
              return $currencies->getName() . "                ";
          }
      ))
      ->add('Publier',      SubmitType::class)
    ;


    $builder->addEventListener(
      FormEvents::PRE_SET_DATA,
      function(FormEvent $event) {

        $advert = $event->getData();


        if (null === $advert) {
          return;
        }


        if (!$advert->getPublished() || null === $advert->getId()) {

          $event->getForm()->add('published', CheckboxType::class, array('required' => false));
        } else {

          $event->getForm()->remove('published');
        }
      }
    );
  }

  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults(array(
      'data_class' => 'OC\PlatformBundle\Entity\Advert'
    ));
  }
}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php


namespace OC\PlatformBundle\Controller;

use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Event\MessagePostEvent;
use OC\PlatformBundle\Event\PlatformEvents;
use OC\PlatformBundle\Form\AdvertEditType;
use OC\PlatformBundle\Form\AdvertType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AdvertController extends Controller
{
  public function indexAction($page)
  {
    if ($page < 1) {
      throw new NotFoundHttpException('Page "'.$page.'" inexistante.');
    }



    $nbPerPage = 4;


    $listAdverts = $this->getDoctrine()
      ->getManager()
      ->getRepository('OCPlatformBundle:Advert')
      ->getAdverts($page, $nbPerPage)
    ;


    $nbPages = ceil(count($listAdverts) / $nbPerPage);

      if ($nbPages == 0) {


          return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
              'listAdverts' => array(),
              'nbPages'     => 1,
              'page'        => 1,
          ));


      }



    if ($page > $nbPages) {
      throw $this->createNotFoundException("La page ".$page." n'existe pas.");
    }




    return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
      'listAdverts' => $listAdverts,
      'nbPages'     => $nbPages,
      'page'        => $page,
    ));


  }

  public function viewAction(Advert $advert)
  {
    $em = $this->getDoctrine()->getManager();


    $listApplications = $em
      ->getRepository('OCPlatformBundle:Application')
      ->findBy(array('advert' => $advert))
    ;


    $listAdvertSkills = $em
      ->getRepository('OCPlatformBundle:AdvertSkill')
      ->findBy(array('advert' => $advert))
    ;

    return $this->render('OCPlatformBundle:Advert:view.html.twig', array(
      'advert'           => $advert,
      'listApplications' => $listApplications,
      'listAdvertSkills' => $listAdvertSkills,
    ));
  }

  /**
   * @Security("has_role('ROLE_AUTEUR')")
   */
  public function addAction(Request $request)
  {



    $advert = new Advert();
    $form   = $this->get('form.factory')->create(AdvertType::class, $advert);

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

      $event = new MessagePostEvent($advert->getContent(), $this->getUser());


      $this->get('event_dispatcher')->dispatch(PlatformEvents::POST_MESSAGE, $event);


      $advert->setContent($event->getMessage());

      $em = $this->getDoctrine()->getManager();
      $em->persist($advert);
      $em->flush();

      $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');

      return $this->redirectToRoute('oc_platform_view', array('id' => $advert->getId()));
    }

    return $this->render('OCPlatformBundle:Advert:add.html.twig', array(
      'form' => $form->createView(),
    ));
  }

  public function editAction(Advert $advert, Request $request)
  {
    $form = $this->get('form.factory')->create(AdvertEditType::class, $advert);

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

      $em = $this->getDoctrine()->getManager();
      $em->flush();

      $request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée.');

      return $this->redirectToRoute('oc_platform_view', array('id' => $advert->getId()));
    }

    return $this->render('OCPlatformBundle:Advert:edit.html.twig', array(
      'advert' => $advert,
      'form'   => $form->createView(),
    ));
  }

  public function deleteAction(Request $request, Advert $advert)
  {
    $em = $this->getDoctrine()->getManager();



    $form = $this->get('form.factory')->create();

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
      $em->remove($advert);
      $em->flush();

      $request->getSession()->getFlashBag()->add('info', "L'annonce a bien été supprimée.");

      return $this->redirectToRoute('oc_platform_home');
    }
    
    return $this->render('OCPlatformBundle:Advert:delete.html.twig', array(
      'advert' => $advert,
      'form'   => $form->createView(),
    ));
  }

  public function menuAction($limit)
  {
    $em = $this->getDoctrine()->getManager();

    $listAdverts = $em->getRepository('OCPlatformBundle:Advert')->findBy(
      array(),
      array('date' => 'desc'),
      $limit,
      0
    );

    return $this->render('OCPlatformBundle:Advert:menu.html.twig', array(
      'listAdverts' => $listAdverts
    ));
  }


  public function translationAction($name)
  {
    return $this->render('OCPlatformBundle:Advert:translation.html.twig', array(
      'name' => $name
    ));
  }

  /**
   * @ParamConverter("json")
   */
  public function ParamConverterAction($json)
  {
    return new Response(print_r($json, true));
  }
}

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/add.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block ocplatform_body %}

<div class="alert alert-info mb-5 col-md-8" role="alert">

    Attention : cette annonce sera ajoutée directement
    sur la page d'accueil après validation du formulaire.

</div>


    <div class="card p-5 mb-5">
        <h3 >Ajouter une annonce</h3>
        {{ include("OCPlatformBundle:Advert:form.html.twig") }}

    </div>


{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    <div class="card p-5 text-center">

  <h2>Supprimer une annonce</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
  </p>


  <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-primary">
      <i class="fa fa-chevron-left mr-2"></i>
      Retour à l'annonce
    </a>

    <input type="submit" value="Supprimer" class="btn btn-danger" />

    {{ form_rest(form) }}
  </form>
    </div>
{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <div class="alert alert-info mb-5 col-md-8" role="alert">

    Attention : cette annonce sera ajoutée directement
    sur la page d'accueil après validation du formulaire.

    <p>
      <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-light-blue mt-2">
        <i class="fa fa-chevron-left mr-2"></i>
        Retour à l'annonce
      </a>
    </p>

  </div>


  <div class="card p-5 mb-5">
    <h3 >Modifier une annonce</h3>
      {{ include("OCPlatformBundle:Advert:form.html.twig") }}

  </div>


{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
<div class="well">
  {{ form_start(form, {'attr': {'class': ''}}) }}

  {{ form_errors(form) }}

    <div class="d-none">
  {% if form.date is defined %}
    {{ form_row(form.date) }}
  {% endif %}
    </div>







    <div class="md-form mb-5">

        {{ form_label(form.title, "Titre") }}


        {{ form_errors(form.title) }}



        {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}

    </div>



    <div class="md-form mb-5">

        {{ form_label(form.author, "Auteur") }}


        {{ form_errors(form.author) }}



        {{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}

    </div>

    <div class="md-form mb-5">

        {{ form_label(form.mail, "Contact (mail ou téléphone)") }}


        {{ form_errors(form.mail) }}

        {{ form_widget(form.mail, {'attr': {'class': 'form-control'}}) }}

    </div>



    <div class="md-form mb-5">

        {{ form_label(form.content, "Contenu de l'annonce") }}

        {{ form_errors(form.content) }}


        {{ form_widget(form.content, {'attr': {'class': 'md-textarea form-control'}}) }}

    </div>



    {% if form.published is defined %}
    <div class="form-check my-4 text-muted">
        {{ form_widget(form.published, {'attr': {'class': 'form-check-input'}}) }}

        {{ form_label(form.published, "visible sur le site") }}
    </div>
  {% endif %}



    <div class="md-form mb-5">
        <div class=" alert-warning">
            {{ form_errors(form.image, {'attr': {'class': ''}}) }}

        </div>

        <div class="file-field">
            <div class="btn btn-primary btn-sm float-left">
                <span>Choisir une image</span>

                {{ form_widget(form.image) }}
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text" placeholder="L'image est optionnelle mais augmente vos chance de recruter">
            </div>
        </div>
    </div>


  <p class="text-muted mb-0"> {{ form_label(form.categories) }}</p>
    <div class="form-check checkbox-orange mb-5">


        {{ form_errors(form.categories) }}




        {{ form_widget(form.categories, {'attr': {'class': 'form-control'}}) }}

    </div>




  {{ form_widget(form.Publier, {'attr': {'class': 'btn btn-primary'}}) }}


  {{ form_rest(form) }}


  {{ form_end(form) }}
</div>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


<script type="text/javascript">
  $(document).ready(function() {


    var $container = $('div#advert_categories');

    var index = $container.find(':input').length;


    $('#add_category').click(function(e) {
      addCategory($container);

      e.preventDefault();
      return false;
    });

    if (index == 0) {
      addCategory($container);
    } else {

      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }


    function addCategory($container) {

      var template = $container.attr('data-prototype')
        .replace(/__name__label__/g, 'Catégorie n°' + (index+1))
        .replace(/__name__/g,        index)
      ;


      var $prototype = $(template);


      addDeleteLink($prototype);

      $container.append($prototype);

      index++;
    }


    function addDeleteLink($prototype) {

      var $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');


      $prototype.append($deleteLink);


      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault();
        return false;
      });
    }
  });
</script>

src/OC/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

    {% for message in app.session.flashbag.get('info') %}
        <div class="alert alert-info text-center">Message flash : {{ message }}</div>
    {% endfor %}

    <h2 class="text-muted">Annonces</h2>



    <div class="list-group mb-5">

        {% for advert in listAdverts %}

            <a href="{{ path('oc_platform_view', {'id': advert.id}) }}"
               class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ advert.title }}</h5>
                    <small>{{ advert.date|date('d/m/Y') }}</small>
                </div>
                <p class="mb-1">{{ advert.content }}</p>
                <small>par {{ advert.author }}</small>
            </a>

        {% else %}
            Il n'y a aucune annonce pour le moment
        {% endfor %}

    </div>

{% if listAdverts %}
    <!--Pagination -->
    <nav aria-label="pagination example">
        <ul class="pagination pagination-circle pg-blue mb-0">

            {% for p in range(1, nbPages) %}
                <li{% if p == page %} class=" page-item active" {% else %} class="page-item" {% endif %}>
                    <a class="page-link" href="{{ path('oc_platform_home', {'page': p}) }}">{{ p }}</a>
                </li>
            {% endfor %}

        </ul>
    </nav>

{% endif %}

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
<ul class="list-group">
  {% for advert in listAdverts %}
    <li >
      <a class=" text-muted " href="{{ path('oc_platform_view', {'id': advert.id}) }}">


          {% if advert.title|length < 16 %}
              {{ advert.title }}

          {% else %}
              {{ advert.title|striptags|slice(0, 15)|raw }}...

          {% endif %}







        <span class="badge badge-primary badge-pill ml-2">{{ advert.id }}</span>
      </a>

    </li>
  {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/translation.html.twig
<html>
  <body>
    {{ 'hello'|trans({'%name%': name}) }}
    <br>
    Aujourd'hui nous sommes le {{ 'now'|localizeddate('full', 'none') }} et il est {{ 'now'|localizeddate('none', 'short') }}
  </body>
</html>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
    Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}



    {% if not advert.categories.empty %}
        Categories :
        {% for category in advert.categories %}
            <span class="badge badge-pill light-blue">     {{ category.name }} </span>
        {% endfor %}

    {% endif %}



        <div class="card p-5 mt-4">
            <div class="row">
        <div class="col-md-7">




            <h2>{{ advert.title }}</h2>
            <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

            <div class="well mt-3">
                {{ advert.content }}
            </div>



            {% if listAdvertSkills|length > 0 %}
                <div>
                    Cette annonce requiert les compétences suivantes :
                    <ul>
                        {% for advertSkill in listAdvertSkills %}
                            <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <hr>

            <p class="text-muted">Contact : {{ advert.mail }}</p>


            <p class="mt-3">
                <a href="{{ path('oc_platform_home') }}" class="btn btn-primary">
                    <i class="fa fa-chevron-left mr-2"></i>
                    Retour à la liste
                </a>
                <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-primary">
                    <i class="fa fa-edit mr-2"></i>
                    Modifier l'annonce
                </a><br>

                <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
                    <i class="fa fa-trash mr-2"></i>
                    Supprimer
                </a>
            </p>









        </div>
        <div class="col-md-3 offset-1">


            {% if advert.image is not null %}
                <div class="card card-cascade wider mb-r">

                    <div class="view">
                        <img
                                src="{{ asset(advert.image.webPath) }}"
                                alt="{{ advert.image.alt }}"
                                class="img-fluid"
                        />

                    </div>
           </div>
            {% endif %}

        </div>
    </div>
    </div>






{% endblock %}